global:
  namespace: fordav 

persistentVolumeClaim:
  efs: "efs-fordav"
  fsx: "fsx-fordav"

fordav:
  name: fordav-data-service 
  image:
    uri:
    policy: Always
  replicaCount: 2
  maxReplicaCount: 10
  requests:
    memory: "72Gi"
    cpu: "8000m"
  metric:
    name: "memory"
    average: "50"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 600
    scaleDown:
      stabilizationWindowSeconds: 3600
  config:
    dir: "/etc/config"
    path: "fordav-data-service.conf"
  serviceAccount:
    name: fordav-data-service-sa
    roleArn: 

configMap:
  {
    "servers": "",
    "kafka_topic": "fordav",
    "database": {
        "dbname": "mozart",
        "host": "",
        "user": "admin",
        "password": "",
    },
    "dynamodb": {
      "data_request_table": ""
    },
    "dataset": {
      "schema_name": "fordav",
      "rosutil_classname": "fordav_ros_util.DatasetRosUtil"
    },
    "data_store": {
        "fsx": {
            "root": "/fsx",
            "rosbag": "/fsx/rosbag"
        },
        "efs": {
            "root": "/efs",
            "rosbag": "/efs/rosbag"
        },
        "s3": {
            "rosbag_bucket": "",
            "rosbag_prefix": "rosbag/"
        },
        "input": "fsx"
    },
    "calibration": {
      "cal_bucket": "",
      "cal_key": "fordav/data/Calibration"
    }
  }
