apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-fordav
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0e386769564ce30a5
    volumeAttributes:
      dnsname: fs-0e386769564ce30a5.fsx.us-west-2.amazonaws.com
      mountname: eiuddbev
