apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-fordav
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-xxxxxxxxxxxxxxxxx
    volumeAttributes:
      dnsname: fs-xxxxxxxxxxxxxxxxx.fsx.xx-xxxx-x.amazonaws.com
      mountname: xxxxxxxx
