global:
  namespace: a2d2 

persistentVolumeClaim:
  efs: "efs-a2d2"
  fsx: "fsx-a2d2"

a2d2:
  name: a2d2-rosbridge 
  image:
    uri: '' 
    policy: Always
  replicaCount: 2
  maxReplicaCount: 10
  requests:
    memory: "72Gi"
    cpu: "8000m"
  metric:
    name: "memory"
    average: "50"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 600
    scaleDown:
      stabilizationWindowSeconds: 3600
  config:
    dir: "/etc/config"
    path: "a2d2-rosbridge.conf"
  serviceAccount:
    name: a2d2-rosbridge-sa
    roleArn: ""

rosbridge:
  port: 9090 
  target_port: 9090 
  internal: "true"
  source_cidr: "0.0.0.0/0"

configMap:
  {
    "database": {
        "dbname": "mozart",
        "host": "",
        "user": "admin",
        "password": ""
    },
    "dynamodb": {
      "data_request_table": ""
    },
    "data_store": {
        "fsx": {
            "root": "/fsx",
            "rosbag": "/fsx/rosbag"
        },
        "efs": {
            "root": "/efs",
            "rosbag": "/efs/rosbag"
        },
        "s3": {
            "rosbag_bucket": "",
            "rosbag_prefix": "rosbag/"
        },
        "input": "fsx"
    },
    "calibration": {
      "cal_bucket": "",
      "cal_key": "a2d2/cams_lidars.json"
    }
  }
